# Scoring by Player Origin - both previous team and hometown

## Dependencies and Setup

In [37]:
import os
import sys
from pathlib import Path
import pandas as pd
import regex as re

import numpy as np
import requests
from bs4 import BeautifulSoup
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
import matplotlib.font_manager as fm
from matplotlib.font_manager import FontProperties
from matplotlib.offsetbox import OffsetImage
from matplotlib.ticker import PercentFormatter
from matplotlib.ticker import ScalarFormatter
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
from PIL import Image

# ======= BASE PATHS =======
try:
    # Works when running as a script
    base_dir = Path(__file__).resolve().parent
except NameError:
    # Fallback for notebooks or interactive mode
    base_dir = Path.cwd()

project_root = base_dir.parent.parent


# ======= DATA FOLDERS =======
temp_folder = project_root / "TEMP"
data_folder = project_root / "data"
roster_folder = data_folder / "player_info"
school_info_folder = data_folder / "school_info"

# ======= IMAGE FOLDERS =======
img_folder = project_root / "images"
logo_folder = img_folder / "logos"
background_folder = img_folder / "background"
plot_folder = project_root / "TEMP" / "IMAGE" / "scoring_origins"

# ======= IMPORT CONFIG =======
import config  # now you can import config.py

# ======= LOAD DATA =======
roster_file = roster_folder / "roster_10_30_25.csv"
roster_df = pd.read_csv(roster_file)
roster_df["Current Team"] = roster_df["Current Team"].replace("RPI", "Rensselaer")

print(roster_df.columns)

school_info_file = school_info_folder / "arena_school_info.csv"
school_info_df = pd.read_csv(school_info_file)

# Check the Config import
# print((config_folder / "config.py").read_text())

Index(['Current Team', 'Last_Name', 'First_Name', 'No', 'Position', 'Yr', 'Ht',
       'Wt', 'DOB', 'Hometown', 'Height_Inches', 'Draft_Year', 'NHL_Team',
       'D_Round', 'Last Team', 'League', 'City', 'State_Province', 'Country'],
      dtype='object')

## Transform the Roster data for easy Merge

In [38]:
# Examine the roster data
# roster_df.head()
# roster_df.info()
# print(roster_df.columns)
# school_info_df.head()

In [39]:
## # Combine First and last name in roster_df to match player_ytd_df

# Clean white space from names
roster_df["First_Name"] = roster_df["First_Name"].str.strip()
roster_df["Last_Name"] = roster_df["Last_Name"].str.strip()
roster_df["Clean_Player"] = roster_df["First_Name"] + " " + roster_df["Last_Name"]
# Strip any leading/trailing whitespace
roster_df["Clean_Player"] = roster_df["Clean_Player"].str.strip()
# Rename Current Team to match player_ytd_df
roster_df = roster_df.rename(columns={"Current Team": "Team"})
# Reorder columns for easier viewing
#Order of columns
# ["No","Team","Clean_Player", "First_Name","Last_Name", 'Position', 'Yr', 'Ht', 'Wt', 'DOB', 'Hometown', 'Height_Inches', 'Draft_Year', 'NHL_Team', 'D_Round', 'Last Team', 'League', 'City', 'State_Province', 'Country']
roster_df = roster_df[["No","Team","Clean_Player", "First_Name","Last_Name", 'Position', 'Yr', 'Ht', 'Wt', 'DOB', 'Hometown', 'Height_Inches', 'Draft_Year', 'NHL_Team', 'D_Round', 'Last Team', 'League', 'City', 'State_Province', 'Country']]    




roster_df.head()

## State_Province Value Counts
check_states = roster_df["State_Province"].value_counts(dropna=False)
check_states

State_Province
Minnesota           217
Ontario             211
British Columbia    124
Alberta             116
New York             98
                   ...
Delaware              1
Germany               1
JPN                   1
Utah                  1
Okla.                 1
Name: count, Length: 73, dtype: int64

In [40]:
### Roster Modifications to make up for incomplete data ###

### Replace bad values in State_Province column
state_province_corrections = {"Okla.": "Oklahoma", "D.C": "District of Columbia"
}
# Apply state/province corrections
roster_df["State_Province"] = roster_df["State_Province"].replace(state_province_corrections)

### Replace country abbreviations with full country names
country_corrections = {"CYM": "Cayman Islands", "JPN": "Japan", "RUS": "Russia"
}
# Apply country corrections
roster_df["Country"] = roster_df["Country"].replace(country_corrections)

########## HOTFIX FOR BAD LAST_TEAM / LEAGUE DATA ##########
# Correct Adam Valentini - Listed as Canada U18 but that was just a tourney. he actually played in the USHL
roster_df.loc[roster_df["Clean_Player"] == "Adam Valentini", "Last Team"] = "Chicago Steel"
roster_df.loc[roster_df["Clean_Player"] == "Adam Valentini", "League"] = "USHL"

# Correct Tanner Hartman - Listed as NCAA D3 which is screwing up the classification - change that to DIII
roster_df.loc[roster_df["Clean_Player"] == "Tanner Hartman", "League"] = "DIII"

# Correct Justin Solovey - Team Muskegon Lumberjacks, League USHL
roster_df.loc[roster_df["Clean_Player"] == "Justin Solovey", "Last Team"] = "Muskegon Lumberjacks"
roster_df.loc[roster_df["Clean_Player"] == "Justin Solovey", "League"] = "USHL"



# Create List or Dictionary of known players with bad/missing data and their correct last team/league
# Then apply those corrections to the roster_df before classification
corrections = {
    "Anthony Galante": "NAHL",
    "Charles Banquier": "BCHL",
    "Devon Carlstrom": "NAHL",
    "Dominick Campione": "AJHL",
    "Frank Ireland": "NCDC",
    "Graham Harris": "DIII",
    "Johnny Druskinis": "NCAA D1",
    "Jonathan Castagna": "PREP",
    "Joseph Grainda": "NAHL",
    "Kasper Magnussen": "Europe",
    "Maxon Vig": "USHL",
    "Mick Frechette": "PREP",
    "Nicholas Chin-DeGraves": "BCHL",
    "Nick Bernardo": "PREP",
    "Tristan Sarsland": "PREP",
    "Wilson Bjorck": "Europe",
    
}

## Apply corrections to roster_df
for player, league in corrections.items():
    roster_df.loc[roster_df["Clean_Player"] == player, "League"] = league

### Connect to database

In [41]:
## Connect to database using the recent_clean_db path from config.py
import sqlite3

#### CONFIG FILE NOTE WORKING AS EXPECTED - MANUAL FIX ####
data_folder = ('../../data/db/')
# filename = '2025_Feb_13_CLEAN.db'
filename = 'Nov_09_Current_Season_YTD_ROUGH.db'
recent_clean_db = data_folder + filename
########### END MANUAL FIX ###########

conn = sqlite3.connect(recent_clean_db)
cursor = conn.cursor()
print("Connected to database:", config.recent_clean_db)

Connected to database: ../../data/db/Nov_09_Current_Season_YTD_ROUGH.db

### Extract and merge the year to date stats
- Issue - the way the player stats ytd table is created it gives credit for games played to everyone, even if they didn't appear in a game
- ultimately I should change the scraping and aggrigation code so a player only gets credit for a game if TOI_sec is > 0

In [42]:
#### Extract and merge the year to date stats ####
player_ytd_query = """
SELECT * FROM player_stats_ytd
"""

player_ytd_df = pd.read_sql_query(player_ytd_query, conn)
# Replace RPI with Rensselaer to match roster_df
player_ytd_df["Team"] = player_ytd_df["Team"].replace("RPI", "Rensselaer")

## print length of DataFrame and columns
print("Player Stats YTD DataFrame shape:", player_ytd_df.shape)
print(player_ytd_df.columns)
# Drop any rows with TOTAL in the Clean_Player column
player_ytd_df = player_ytd_df[~player_ytd_df['Clean_Player'].str.contains('TOTAL', na=False)]

# Check length of DataFrame and columns after drop

print("Player Stats YTD DataFrame shape:", player_ytd_df.shape)
print(player_ytd_df.columns)

# Close the database connection
conn.close()

Player Stats YTD DataFrame shape: (1579, 14)
Index(['Clean_Player', 'Team', 'G', 'A', 'Pts', 'PlusMinus', 'Shots',
       'TOI_sec', 'PIM', 'FOW', 'FOL', 'Games_Played', 'FO%', 'TOI'],
      dtype='object')
Player Stats YTD DataFrame shape: (1579, 14)
Index(['Clean_Player', 'Team', 'G', 'A', 'Pts', 'PlusMinus', 'Shots',
       'TOI_sec', 'PIM', 'FOW', 'FOL', 'Games_Played', 'FO%', 'TOI'],
      dtype='object')

In [43]:
# Make sure name and team columns are stripped of punctuation, strange characters, and whitespace
player_ytd_df["Clean_Player"] = player_ytd_df["Clean_Player"].str.strip()
player_ytd_df["Team"] = player_ytd_df["Team"].str.strip()
roster_df["Clean_Player"] = roster_df["Clean_Player"].str.strip()
roster_df["Team"] = roster_df["Team"].str.strip()
# Remove any hyphens, periods, ect from team names to match
player_ytd_df["Team"] = player_ytd_df["Team"].str.replace(r'[^\w\s]', ' ', regex=True)
roster_df["Team"] = roster_df["Team"].str.replace(r'[^\w\s]', ' ', regex=True)
# QUICK FIX - Standardize team names with double spaces
# If team name column has double spaces, replace with single space
player_ytd_df["Team"] = player_ytd_df["Team"].str.replace('  ', ' ', regex=False)
roster_df["Team"] = roster_df["Team"].str.replace('  ', ' ', regex=False)

## Merge the two DataFrames on Clean_Player and Team
merged_df = pd.merge(
    player_ytd_df,
    roster_df,
    left_on=["Clean_Player", "Team"],
    right_on=["Clean_Player", "Team"],
    how="left"
)

# Shape and info of merged DataFrame
print("Merged DataFrame shape:", merged_df.shape)
# print(merged_df.columns)
# print(merged_df.head())
merged_df.info()

Merged DataFrame shape: (1579, 32)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1579 entries, 0 to 1578
Data columns (total 32 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Clean_Player    1579 non-null   object
 1   Team            1579 non-null   object
 2   G               1579 non-null   int64
 3   A               1579 non-null   int64
 4   Pts             1579 non-null   int64
 5   PlusMinus       1579 non-null   int64
 6   Shots           1579 non-null   int64
 7   TOI_sec         1579 non-null   float64
 8   PIM             1579 non-null   int64
 9   FOW             1579 non-null   float64
 10  FOL             1579 non-null   float64
 11  Games_Played    1579 non-null   int64
 12  FO%             800 non-null    float64
 13  TOI             1579 non-null   object
 14  No              1578 non-null   float64
 15  First_Name      1578 non-null   object
 16  Last_Name       1578 non-null   object
 17  Position        1578 non-null   object
 18  Yr              1578 non-null   object
 19  Ht              1578 non-null   object
 20  Wt              1578 non-null   float64
 21  DOB             1578 non-null   object
 22  Hometown        1578 non-null   object
 23  Height_Inches   1578 non-null   float64
 24  Draft_Year      244 non-null    float64
 25  NHL_Team        244 non-null    object
 26  D_Round         244 non-null    float64
 27  Last Team       1578 non-null   object
 28  League          1571 non-null   object
 29  City            1578 non-null   object
 30  State_Province  1578 non-null   object
 31  Country         1578 non-null   object
dtypes: float64(9), int64(7), object(16)
memory usage: 394.9+ KB

### NEED TO DEAL WITH THIS WEIRD ONE EDGE CASE

In [44]:
## Export merged DataFrame to CSV for examination
# output_file = "../../TEMP/merged_player_stats_roster_test_1.csv"

## Show me a random selection of ten rows that didn't match for merge
## ie no current team, last name, ect
missing_team_df = merged_df[merged_df["First_Name"].isnull()]

missing_team_df

,Clean_Player,Team,G,A,Pts,PlusMinus,Shots,TOI_sec,PIM,FOW,...,Hometown,Height_Inches,Draft_Year,NHL_Team,D_Round,Last Team,League,City,State_Province,Country
1070,Maxon Vig,Bemidji State,1,1,2,8,11,11281.0,8,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Cleaning and Validation

### Filter out players with no TOI and goalies
- Remove players that haven't appeared in a game at all this year (TOI_sec = 0)
    -can't depend on YTD stats games played until we fix the scraping code
- Filter out goaltenders as non skaters - looking at offensive production so goalies are irrelivant (despite the assists they may get from time to time)

In [45]:
## Print Value COunt of Position column
# print(merged_df['Position'].value_counts())

In [46]:
### Print dataframe stats for to keep track of filtering steps
original_count = merged_df.shape[0]
print("Merged DataFrame shape before filtering:", merged_df.shape)

### Filter out players with no TOI and goalies
# Remove players that haven't appeared in a game at all this year (TOI_sec = 0)
# Remove any Rows where TOI_sec is 0 or NaN - These are goalies or players with no time on ice
merged_df = merged_df[(merged_df["TOI_sec"] > 0) & (~merged_df["TOI_sec"].isna())]
first_step_count = merged_df.shape[0]

## Check the shape after filtering
print("Merged DataFrame shape after filtering TOI_sec > 0:", merged_df.shape)
# Number of players removed
print("Players removed after filtering TOI_sec > 0:", original_count - first_step_count)

### DO NOT NEED TO FILTER FOR GOALIES BECAUSE PLAYER_YTD_STATS TABLE ONLY HAS TOI FOR SKATERS
# Filter out goaltenders as non skaters - looking at offensive production so goalies are irrelivant (despite the assists they may get from time to time)
# Strip any whitespace from Position column
# merged_df["Position"] = merged_df["Position"].str.strip()
# merged_df = merged_df[merged_df["Position"] != "Goaltenders"]
# no_goalie_count = merged_df.shape[0]
## Check the shape after filtering
# print("Merged DataFrame shape after filtering out Goalies:", merged_df.shape)
# # Number of players removed
# print("Players removed by filtering out Goalies:", first_step_count - no_goalie_count)

Merged DataFrame shape before filtering: (1579, 32)
Merged DataFrame shape after filtering TOI_sec > 0: (1446, 32)
Players removed after filtering TOI_sec > 0: 133

In [47]:
# merged_df.columns

## Quick Explore of Origin Data

In [48]:
## Value count of 'League' column
# print(merged_df['League'].value_counts())

# ### Country value counts
# print(merged_df['Country'].value_counts())

# # Check for any players that have null or 0 TOI but have Games Played > 0
# null_toi_df = merged_df[(merged_df["TOI_sec"].isnull()) | (merged_df["TOI_sec"] == 0) & (merged_df["Games_Played"] > 0)]
# null_toi_df

In [49]:
# Correct Maxon Vig - Team Cedar Rapids RoughRiders, League USHL
## Couldn't do it before because he was not in original roster_df but now he is in merged_df
merged_df.loc[merged_df["Clean_Player"] == "Maxon Vig", "Last Team"] = "Cedar Rapids RoughRiders"
merged_df.loc[merged_df["Clean_Player"] == "Maxon Vig", "League"] = "USHL"

### Clean and Classify Previous Team / League columns
- put into the same bins as used on the Team Construction Visual
- Copied code from there with a few changes made based on feedback / missed classifications

In [50]:
### Reusing League and Team Classification function and libraries from team_construction_visual_workbook import classify_previous_team, classify_previous_league

# ----------------------------
# 1) Rename merged_df to df for easier to fit in with existing code
# -----------------------------
df = merged_df.copy()

# -----------------------------
# 2) Classification helpers
# -----------------------------
def _norm_set(strings):
    return { _norm(s) for s in strings }

def _norm(s: str) -> str:
    if pd.isna(s):
        return ""
    s = str(s).strip().upper()
    s = re.sub(r"[.\u2010-\u2015\-–—]+", " ", s)  # unify hyphen-like chars to space
    s = re.sub(r"\s+", " ", s).strip()
    return s

def _norm_set(strings):
    return { _norm(s) for s in strings }

NTDP_TEAM_HINTS_RAW = (
    "USA U 18", "US U 18", "USA U18", "US U18",
    "USA U 17", "US U 17", "USA U17", "US U17",
    "NTDP", "USNTDP", "US NATIONAL TEAM", "US DEV PROGRAM", "US DEVELOPMENT PROGRAM"
)
NTDP_LEAGUE_HINTS_RAW = ("NTDP",)

D1_CONFS_RAW = {"ECAC","CCHA","NCHC","HEA","B10","AHA","INDEPENDENTS","D I IND","NCAA"}

CJHL_LEAGUES_RAW = {"BCHL","AJHL","SJHL","OJHL", "MJHL", "CCHL","MHL"}

US_TIER1_RAW = {"USHL"}
US_TIER2_RAW = {"NAHL","NCDC"}
US_OTHER_RAW  = {"USPHL","NA3HL", "PREP", "PHC", "USHS", "CISAA", "DIII", "D-III"}

CHL_RAW = {"OHL","WHL","QMJHL", "MJAHL"}

EURO_HINTS_RAW = {
    "J20 NATIONELL","J18 REGION","U20 SM SARJA","U18","U20","SM SARJA",
    "SHL","ICEHL","ALPSHL","LIIGA","MHL RUSSIA","KHL, ICEHL","KHL","DEL", "EC-KAC",
}

EURO_TEAM_HINTS_RAW = {
    "KalPa U20", "Frölunda HC", "Malmo", "Jokerit U20", "U20 SM Sarja-Pelicans",
    "Tappara J20", "Djurgårdens IF", "Leksands IF",
}

RUSSIAN_MHL_TEAM_HINTS_RAW = (
    "KRASNAYA","LOKO","MOSKVA","MOSCOW","ST PETERSBURG","SKA","LOKOMOTIV",
    "DMITROV","CHELYABINSK","OMSK","NOVOSIBIRSK","MAGNITOGORSK","NIZHNY","YAROSLAVL",
)

# Normalize them
NTDP_TEAM_HINTS       = _norm_set(NTDP_TEAM_HINTS_RAW)
NTDP_LEAGUE_HINTS     = _norm_set(NTDP_LEAGUE_HINTS_RAW)
D1_CONFS              = _norm_set(D1_CONFS_RAW)
CJHL_LEAGUES          = _norm_set(CJHL_LEAGUES_RAW)
US_TIER1              = _norm_set(US_TIER1_RAW)
US_TIER2              = _norm_set(US_TIER2_RAW)
US_OTHER              = _norm_set(US_OTHER_RAW)
CHL                   = _norm_set(CHL_RAW)
EURO_HINTS            = _norm_set(EURO_HINTS_RAW)
EURO_TEAM_HINTS       = _norm_set(EURO_TEAM_HINTS_RAW)
RUSSIAN_MHL_TEAM_HINTS = _norm_set(RUSSIAN_MHL_TEAM_HINTS_RAW)

PRO_HINTS = ("AHL","ECHL")

BIN_ORDER = [
    "NTDP",
    "USHL (non‑NTDP)",
    "NAHL/NCDC",
    "US (DIII/Prep/Other)",
    "CHL (Major Junior)",
    "CJHL (Canadian Jr A)",
    "U SPORTS",
    "Europe",
    "NCAA D1 Transfers",
    "Pro (AHL/ECHL/Other)",
    "Other/Various/Unknown"
    
]

COLOR_MAP = {
    "NTDP": "#0057B8",
    "USHL (non‑NTDP)": "#1E90FF",
    "NAHL/NCDC": "#63B8FF",
    "US (DIII/Prep/Other)": "#B0E2FF",
    "CHL (Major Junior)": "#B22222",
    "CJHL (Canadian Jr A)": "#FF7F7F",
    "U SPORTS": "#FADBD8",
    "Europe": "#F0E130",
    "NCAA D1 Transfers": "#696969",
    "Pro (AHL/ECHL/Other)": "#000000",
    "Other/Various/Unknown": "#A9A9A9"
}

def classify_prev_bin(last_team: str, league: str) -> str:
    t = _norm(last_team)
    l = _norm(league)

    # NTDP carve-out first
    if any(h in t for h in NTDP_TEAM_HINTS) or any(h == l for h in NTDP_LEAGUE_HINTS):
        return "NTDP"

    # D3/Prep -> Other
    if l in US_OTHER:
        return "US (DIII/Prep/Other)"

    # NCAA D1 transfers
    if (l in D1_CONFS) or ("NCAA" in l and l != ""):
        return "NCAA D1 Transfers"

    # U SPORTS
    if l in {"USPORTS", "U SPORTS"}:
        return "U SPORTS"

    # CHL
    if l in CHL:
        return "CHL (Major Junior)"

    # MHL ambiguity
    if l == "MHL":
        if any(k in t for k in RUSSIAN_MHL_TEAM_HINTS):
            return "Europe"
        else:
            return "CJHL (Canadian Jr A)"

    # CJHL
    if l in CJHL_LEAGUES:
        return "CJHL (Canadian Jr A)"



    # US juniors
    if l in US_TIER1:
        return "USHL (non‑NTDP)"
    if l in US_TIER2:
        return "NAHL/NCDC"
    
    # Pro leagues
    if any(h in l for h in PRO_HINTS):
        return "Pro (AHL/ECHL/Other)"

    # Europe consolidated
    if l in EURO_HINTS:
        return "Europe"
    if t in EURO_TEAM_HINTS:
        return "Europe"




    # Fallbacks/Unknown
    # if l == "" or pd.isna(league):
    #     return "Other/Various/Unknown"
    
    if "U SPORTS" in t:
        return "U SPORTS"
    if "IF Sundsvall" in t:  # edge case
        return "Europe"


    return "Other/Various/Unknown"


# Apply classification to the raw roster
df["Prev_League_Bin"] = df.apply(lambda r: classify_prev_bin(r.get("Last Team", np.nan),
                                                             r.get("League", np.nan)), axis=1)
df["Prev_League_Bin"] = pd.Categorical(df["Prev_League_Bin"], categories=BIN_ORDER, ordered=True)

# Save classified to temp_folder
# timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
# out_file = os.path.join(temp_folder, f"roster_classified_{timestamp}.csv")
# df.to_csv(out_file, index=False)


# show quick counts
overall_counts = (df["Prev_League_Bin"]
                  .value_counts(dropna=False)
                  .reindex(BIN_ORDER)
                  .fillna(0).astype(int))

print("Overall Counts by Prev_League_Bin")
print(overall_counts.reset_index().rename(columns={"index":"Bin","Prev_League_Bin":"Count"}))

Overall Counts by Prev_League_Bin
                    Count  count
0                    NTDP     41
1         USHL (non‑NTDP)    436
2               NAHL/NCDC    196
3    US (DIII/Prep/Other)     11
4      CHL (Major Junior)    147
5    CJHL (Canadian Jr A)    311
6                U SPORTS     34
7                  Europe     24
8       NCAA D1 Transfers    241
9    Pro (AHL/ECHL/Other)      5
10  Other/Various/Unknown      0

In [51]:
## Show The Other/Various/Unknown players
other_unknown_df = df[df["Prev_League_Bin"] == "Other/Various/Unknown"]
other_unknown_df = other_unknown_df[["Clean_Player", "Team", "Last Team", "League", "Prev_League_Bin" ]]
# other_unknown_df

### Generate table of the number of players on each team

In [52]:
### Create a table of the number of players on each team from the various leagues
team_league_counts = (df
                      .groupby(["Team", "Prev_League_Bin"])
                      .size()
                      .unstack(fill_value=0)
                      .reindex(columns=BIN_ORDER, fill_value=0)
                     )  

# Reorder so CHL is first column after Team
cols = team_league_counts.columns.tolist()
cols = cols[-6:] + cols[:-1]  # Move last column to first position
team_league_counts = team_league_counts[cols]



# team_league_counts

C:\Users\jbanc\AppData\Local\Temp\ipykernel_12636\3039452061.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["Team", "Prev_League_Bin"])

### Adgrigate Stats using the new class bins

In [53]:
### Group by Prev_League_Bin and aggregate stats (G, A, Pts, PlusMinus, Shots, TOI_sec, PIM)

agg_stats = {
    "Games_Played": "sum",
    "G": "sum",
    "A": "sum",
    "Pts": "sum",
    "PlusMinus": "sum",
    "Shots": "sum",
    "TOI_sec": "sum",
    "PIM": "sum",
}
agg_df = df.groupby("Prev_League_Bin").agg(agg_stats).reset_index()
# # creat column for count of players in each bin
# agg_df["Player_Count"] = df["Prev_League_Bin"].value_counts().reindex(agg_df["Prev_League_Bin"]).values
# # Create AVG games played per player column
# agg_df["Avg_Games Played"] = agg_df["Games_Played"] / agg_df["Player_Count"]

# # Reorder Columns to put player_count right after Prev_League_Bin
# agg_df = agg_df[["Prev_League_Bin", "Player_Count", "Games_Played", "Avg_Games Played"] + list(agg_stats.keys())]


agg_df

C:\Users\jbanc\AppData\Local\Temp\ipykernel_12636\1377335929.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agg_df = df.groupby("Prev_League_Bin").agg(agg_stats).reset_index()

,Prev_League_Bin,Games_Played,G,A,Pts,PlusMinus,Shots,TOI_sec,PIM
0,NTDP,376,96,120,216,26,714,371664.0,282
1,USHL (non‑NTDP),3413,541,957,1498,206,5515,3224775.0,1899
2,NAHL/NCDC,1272,128,248,376,-181,1637,1059386.0,672
3,US (DIII/Prep/Other),76,17,16,33,6,147,72386.0,40
4,CHL (Major Junior),1225,209,359,568,-14,2115,1127930.0,792
5,CJHL (Canadian Jr A),2116,270,472,742,-153,2920,1811622.0,1011
6,U SPORTS,275,51,80,131,-34,454,266383.0,208
7,Europe,158,31,49,80,26,234,135665.0,79
8,NCAA D1 Transfers,2083,350,575,925,-33,3518,2044873.0,1239
9,Pro (AHL/ECHL/Other),44,12,16,28,9,81,51640.0,47
10,Other/Various/Unknown,0,0,0,0,0,0,0.0,0

In [54]:
## Get count of players in each Prev_League_Bin
player_counts = (df["Prev_League_Bin"]
                  .value_counts(dropna=False)
                  .reindex(BIN_ORDER)
                  .fillna(0).astype(int))

# print("Player Counts by Prev_League_Bin")
# print(player_counts.reset_index().rename(columns={"index":"Bin","Prev_League_Bin":" Count"}))

In [55]:
### Divide aggregated stats by player counts to get per player averages
for stat in agg_stats.keys():
    agg_df[stat + "_per_player"] = agg_df[stat] / player_counts.values
# agg_df

## Use the Games_Played column to get per game averages for all stats
for stat in agg_stats.keys():
    agg_df[stat + "_per_game"] = agg_df[stat] / agg_df["Games_Played"]

#### Calulate per 60 minutes stats for each aggregated stat
for stat in agg_stats.keys():
    agg_df[stat + "_per_60min"] = (agg_df[stat] / agg_df["TOI_sec"]) * 3600

In [56]:
#### Calulate per 60 minutes stats for each aggregated stat
for stat in agg_stats.keys():
    agg_df[stat + "_per_60min"] = (agg_df[stat] / (agg_df["TOI_sec"]) * 3600)

In [57]:
# create column for count of players in each bin
agg_df["Player_Count"] = df["Prev_League_Bin"].value_counts().reindex(agg_df["Prev_League_Bin"]).values
# Create AVG games played per player column
agg_df["Avg_Games Played"] = agg_df["Games_Played"] / agg_df["Player_Count"]

# Move Player_Count column to be right after Prev_League_Bin and Avg_Games Played
cols = agg_df.columns.tolist()
cols.insert(1, cols.pop(cols.index("Player_Count")))
cols.insert(3, cols.pop(cols.index("Avg_Games Played")))
agg_df = agg_df[cols]

In [58]:
### Examine the final aggregated DataFrame
agg_df.info()
agg_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 35 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Prev_League_Bin          11 non-null     category
 1   Player_Count             11 non-null     int64
 2   Games_Played             11 non-null     int64
 3   Avg_Games Played         10 non-null     float64
 4   G                        11 non-null     int64
 5   A                        11 non-null     int64
 6   Pts                      11 non-null     int64
 7   PlusMinus                11 non-null     int64
 8   Shots                    11 non-null     int64
 9   TOI_sec                  11 non-null     float64
 10  PIM                      11 non-null     int64
 11  Games_Played_per_player  10 non-null     float64
 12  G_per_player             10 non-null     float64
 13  A_per_player             10 non-null     float64
 14  Pts_per_player           10 non-null     float64
 15  PlusMinus_per_player     10 non-null     float64
 16  Shots_per_player         10 non-null     float64
 17  TOI_sec_per_player       10 non-null     float64
 18  PIM_per_player           10 non-null     float64
 19  Games_Played_per_game    10 non-null     float64
 20  G_per_game               10 non-null     float64
 21  A_per_game               10 non-null     float64
 22  Pts_per_game             10 non-null     float64
 23  PlusMinus_per_game       10 non-null     float64
 24  Shots_per_game           10 non-null     float64
 25  TOI_sec_per_game         10 non-null     float64
 26  PIM_per_game             10 non-null     float64
 27  Games_Played_per_60min   10 non-null     float64
 28  G_per_60min              10 non-null     float64
 29  A_per_60min              10 non-null     float64
 30  Pts_per_60min            10 non-null     float64
 31  PlusMinus_per_60min      10 non-null     float64
 32  Shots_per_60min          10 non-null     float64
 33  TOI_sec_per_60min        10 non-null     float64
 34  PIM_per_60min            10 non-null     float64
dtypes: category(1), float64(26), int64(8)
memory usage: 3.4 KB

,Prev_League_Bin,Player_Count,Games_Played,Avg_Games Played,G,A,Pts,PlusMinus,Shots,TOI_sec,...,TOI_sec_per_game,PIM_per_game,Games_Played_per_60min,G_per_60min,A_per_60min,Pts_per_60min,PlusMinus_per_60min,Shots_per_60min,TOI_sec_per_60min,PIM_per_60min
0,NTDP,41,376,9.170732,96,120,216,26,714,371664.0,...,988.468085,0.750000,3.641999,0.929872,1.162340,2.092212,0.251840,6.915924,3600.0,2.731499
1,USHL (non‑NTDP),436,3413,7.827982,541,957,1498,206,5515,3224775.0,...,944.850571,0.556402,3.810126,0.603949,1.068354,1.672303,0.229970,6.156709,3600.0,2.119962
2,NAHL/NCDC,196,1272,6.489796,128,248,376,-181,1637,1059386.0,...,832.850629,0.528302,4.322504,0.434969,0.842752,1.277721,-0.615073,5.562845,3600.0,2.283587
3,US (DIII/Prep/Other),11,76,6.909091,17,16,33,6,147,72386.0,...,952.447368,0.526316,3.779736,0.845467,0.795734,1.641201,0.298400,7.310806,3600.0,1.989335
4,CHL (Major Junior),147,1225,8.333333,209,359,568,-14,2115,1127930.0,...,920.759184,0.646531,3.909817,0.667063,1.145816,1.812878,-0.044684,6.750419,3600.0,2.527816
5,CJHL (Canadian Jr A),311,2116,6.803859,270,472,742,-153,2920,1811622.0,...,856.154064,0.477788,4.204851,0.536536,0.937944,1.474480,-0.304037,5.802535,3600.0,2.009028
6,U SPORTS,34,275,8.088235,51,80,131,-34,454,266383.0,...,968.665455,0.756364,3.716453,0.689233,1.081150,1.770383,-0.459489,6.135527,3600.0,2.810990
7,Europe,24,158,6.583333,31,49,80,26,234,135665.0,...,858.639241,0.500000,4.192680,0.822615,1.300262,2.122876,0.689935,6.209413,3600.0,2.096340
8,NCAA D1 Transfers,241,2083,8.643154,350,575,925,-33,3518,2044873.0,...,981.696111,0.594815,3.667123,0.616175,1.012288,1.628463,-0.058097,6.193441,3600.0,2.181260
9,Pro (AHL/ECHL/Other),5,44,8.800000,12,16,28,9,81,51640.0,...,1173.636364,1.068182,3.067390,0.836561,1.115414,1.951975,0.627421,5.646785,3600.0,3.276530
10,Other/Various/Unknown,0,0,NaN,0,0,0,0,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Plan for Visualizations
- data transformation is looking good to this point. SHould have a few diff. interesting views

- Should I use stacked bars witht he country bins and color grtadiant within?
- Should come up a good visual for the number of games played by each bin of players

## Bin By Country

In [59]:
### Do The Aggrigation by Home Country
country_agg_stats = {
    "Games_Played": "sum",
    "G": "sum",
    "A": "sum",
    "Pts": "sum",
    "PlusMinus": "sum",
    "Shots": "sum",
    "TOI_sec": "sum",
    "PIM": "sum",
}
country_agg_df = merged_df.groupby("Country").agg(country_agg_stats).reset_index()
print(country_agg_df.head(20))

## Get count of players in each Country and calculate per player averages
country_player_counts = (df["Country"]
                    .value_counts(dropna=False)
                    .fillna(0).astype(int))
# print("Player Counts by Country")
# print(country_player_counts.reset_index().rename(columns={"index":"Country","Country":" Count"}))

           Country  Games_Played    G     A   Pts  PlusMinus  Shots  \
0          Austria            23    7    10    17          8     44
1          Belarus            15    4     4     8         -1     15
2           Canada          4082  647  1119  1766       -133   6549
3   Cayman Islands            11    0     4     4         -5     10
4          Croatia             7    0     1     1          3     15
5   Czech Republic            54   13    16    29         -3    122
6          Czechia            11    1     2     3         -8     21
7          Finland           140   24    36    60         10    199
8          Germany             9    0     2     2         -2     12
9    Great Britain             7    0     0     0          1      9
10         Hungary             8    1     2     3          4      7
11           Italy            10    0     0     0         -7     14
12           Japan             7    0     1     1         -1      6
13          Latvia            95   13    16    29        -20    137
14          Norway            37    4    16    20          3     50
15          Russia            72   16    37    53         27    114
16        Scotland             9    3     4     7          0     20
17        Slovakia            87   18    21    39        -13    130
18        Slovenia             2    0     0     0         -1      2
19          Sweden           245   28    64    92        -29    376

      TOI_sec   PIM
0     22769.0     4
1     10860.0     4
2   3743697.0  2423
3     10907.0     4
4      4396.0     2
5     57773.0    30
6     10394.0     2
7    122468.0    69
8      8761.0     2
9      4981.0     6
10     6476.0     2
11     7373.0     8
12     3361.0     0
13    89295.0    56
14    35854.0    14
15    67151.0    68
16     8539.0     2
17    82406.0    40
18     1700.0     2
19   242828.0   105

In [60]:
## Calculate per player averages for each aggregated stat by Country
country_player_counts = country_player_counts.reindex(country_agg_df["Country"])
for stat in country_agg_stats.keys():
    country_agg_df[stat + "_per_player"] = country_agg_df[stat] / country_player_counts.values

# Calculate per game averages for each aggregated stat by Country
for stat in country_agg_stats.keys():
    country_agg_df[stat + "_per_game_played"] = country_agg_df[stat] / country_agg_df["Games_Played"]

## Calculate rate stats per 60 minutes for each aggregated stat by Country
for stat in country_agg_stats.keys():
    country_agg_df[stat + "_per_60min"] = (country_agg_df[stat] / country_agg_df["TOI_sec"]) * 3600

country_agg_df.info()
country_agg_df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Country                       23 non-null     object
 1   Games_Played                  23 non-null     int64
 2   G                             23 non-null     int64
 3   A                             23 non-null     int64
 4   Pts                           23 non-null     int64
 5   PlusMinus                     23 non-null     int64
 6   Shots                         23 non-null     int64
 7   TOI_sec                       23 non-null     float64
 8   PIM                           23 non-null     int64
 9   Games_Played_per_player       23 non-null     float64
 10  G_per_player                  23 non-null     float64
 11  A_per_player                  23 non-null     float64
 12  Pts_per_player                23 non-null     float64
 13  PlusMinus_per_player          23 non-null     float64
 14  Shots_per_player              23 non-null     float64
 15  TOI_sec_per_player            23 non-null     float64
 16  PIM_per_player                23 non-null     float64
 17  Games_Played_per_game_played  23 non-null     float64
 18  G_per_game_played             23 non-null     float64
 19  A_per_game_played             23 non-null     float64
 20  Pts_per_game_played           23 non-null     float64
 21  PlusMinus_per_game_played     23 non-null     float64
 22  Shots_per_game_played         23 non-null     float64
 23  TOI_sec_per_game_played       23 non-null     float64
 24  PIM_per_game_played           23 non-null     float64
 25  Games_Played_per_60min        23 non-null     float64
 26  G_per_60min                   23 non-null     float64
 27  A_per_60min                   23 non-null     float64
 28  Pts_per_60min                 23 non-null     float64
 29  PlusMinus_per_60min           23 non-null     float64
 30  Shots_per_60min               23 non-null     float64
 31  TOI_sec_per_60min             23 non-null     float64
 32  PIM_per_60min                 23 non-null     float64
dtypes: float64(25), int64(7), object(1)
memory usage: 6.1+ KB

,Country,Games_Played,G,A,Pts,PlusMinus,Shots,TOI_sec,PIM,Games_Played_per_player,...,TOI_sec_per_game_played,PIM_per_game_played,Games_Played_per_60min,G_per_60min,A_per_60min,Pts_per_60min,PlusMinus_per_60min,Shots_per_60min,TOI_sec_per_60min,PIM_per_60min
0,Austria,23,7,10,17,8,44,22769.0,4,7.666667,...,989.956522,0.173913,3.636523,1.106768,1.581097,2.687865,1.264878,6.956827,3600.0,0.632439
1,Belarus,15,4,4,8,-1,15,10860.0,4,7.500000,...,724.000000,0.266667,4.972376,1.325967,1.325967,2.651934,-0.331492,4.972376,3600.0,1.325967
2,Canada,4082,647,1119,1766,-133,6549,3743697.0,2423,7.687382,...,917.123224,0.593582,3.925318,0.622166,1.076049,1.698214,-0.127895,6.297625,3600.0,2.329996
3,Cayman Islands,11,0,4,4,-5,10,10907.0,4,5.500000,...,991.545455,0.363636,3.630696,0.000000,1.320253,1.320253,-1.650316,3.300633,3600.0,1.320253
4,Croatia,7,0,1,1,3,15,4396.0,2,7.000000,...,628.000000,0.285714,5.732484,0.000000,0.818926,0.818926,2.456779,12.283894,3600.0,1.637853
5,Czech Republic,54,13,16,29,-3,122,57773.0,30,9.000000,...,1069.870370,0.555556,3.364894,0.810067,0.997006,1.807073,-0.186939,7.602167,3600.0,1.869385
6,Czechia,11,1,2,3,-8,21,10394.0,2,11.000000,...,944.909091,0.181818,3.809890,0.346354,0.692707,1.039061,-2.770829,7.273427,3600.0,0.692707
7,Finland,140,24,36,60,10,199,122468.0,69,6.666667,...,874.771429,0.492857,4.115361,0.705490,1.058236,1.763726,0.293954,5.849691,3600.0,2.028285
8,Germany,9,0,2,2,-2,12,8761.0,2,9.000000,...,973.444444,0.222222,3.698208,0.000000,0.821824,0.821824,-0.821824,4.930944,3600.0,0.821824
9,Great Britain,7,0,0,0,1,9,4981.0,6,7.000000,...,711.571429,0.857143,5.059225,0.000000,0.000000,0.000000,0.722746,6.504718,3600.0,4.336479
10,Hungary,8,1,2,3,4,7,6476.0,2,8.000000,...,809.500000,0.250000,4.447190,0.555899,1.111797,1.667696,2.223595,3.891291,3600.0,1.111797
11,Italy,10,0,0,0,-7,14,7373.0,8,10.000000,...,737.300000,0.800000,4.882680,0.000000,0.000000,0.000000,-3.417876,6.835752,3600.0,3.906144
12,Japan,7,0,1,1,-1,6,3361.0,0,7.000000,...,480.142857,0.000000,7.497769,0.000000,1.071110,1.071110,-1.071110,6.426659,3600.0,0.000000
13,Latvia,95,13,16,29,-20,137,89295.0,56,8.636364,...,939.947368,0.589474,3.830002,0.524105,0.645053,1.169158,-0.806316,5.523266,3600.0,2.257685
14,Norway,37,4,16,20,3,50,35854.0,14,7.400000,...,969.027027,0.378378,3.715067,0.401629,1.606515,2.008144,0.301222,5.020360,3600.0,1.405701
15,Russia,72,16,37,53,27,114,67151.0,68,8.000000,...,932.652778,0.944444,3.859957,0.857768,1.983589,2.841358,1.447484,6.111599,3600.0,3.645515
16,Scotland,9,3,4,7,0,20,8539.0,2,9.000000,...,948.777778,0.222222,3.794355,1.264785,1.686380,2.951165,0.000000,8.431901,3600.0,0.843190
17,Slovakia,87,18,21,39,-13,130,82406.0,40,7.909091,...,947.195402,0.459770,3.800694,0.786351,0.917409,1.703759,-0.567920,5.679198,3600.0,1.747446
18,Slovenia,2,0,0,0,-1,2,1700.0,2,2.000000,...,850.000000,1.000000,4.235294,0.000000,0.000000,0.000000,-2.117647,4.235294,3600.0,4.235294
19,Sweden,245,28,64,92,-29,376,242828.0,105,7.656250,...,991.134694,0.428571,3.632201,0.415109,0.948820,1.363928,-0.429934,5.574316,3600.0,1.556657

## Bin By State / Province

In [61]:
## Examine the State_Province column value counts
state_prov_counts = merged_df['State_Province'].value_counts()
print("State/Province Value Counts")
print(state_prov_counts)

State/Province Value Counts
State_Province
Minnesota           181
Ontario             174
British Columbia    106
Alberta              98
New York             84
                   ...
United Kingdom        1
Delaware              1
Czechia               1
Oklahoma              1
RUS                   1
Name: count, Length: 69, dtype: int64

In [62]:

## Filter out any rows that don't have USA or CAN in the Country column

# print length of merged_df before filtering
print("Merged DataFrame shape before filtering for USA/CAN:", merged_df.shape)
us_can_df = merged_df[(merged_df["Country"] == "USA") | (merged_df["Country"] == "Canada")]

# print length of us_can_df after filtering
print("Filtered DataFrame shape for USA/CAN:", us_can_df.shape)

# Print summary of State_Province values in us_can_df
print("USA/CAN DataFrame State/Province Value Counts")
# USA / Canada Country Value Counts
print(us_can_df['Country'].value_counts())
# State Province Value Counts
print(us_can_df['State_Province'].value_counts())

# Check State Province values of rows filtered out
# filtered_out_df = merged_df[~merged_df.index.isin(us_can_df.index)]
# print("Filtered Out DataFrame State/Province Value Counts")
# print(filtered_out_df['State_Province'].value_counts())

Merged DataFrame shape before filtering for USA/CAN: (1446, 32)
Filtered DataFrame shape for USA/CAN: (1330, 32)
USA/CAN DataFrame State/Province Value Counts
Country
USA       799
Canada    531
Name: count, dtype: int64
State_Province
Minnesota                    181
Ontario                      174
British Columbia             106
Alberta                       98
New York                      84
Massachusetts                 69
Michigan                      68
Quebec                        66
Illinois                      53
California                    45
New Jersey                    37
Saskatchewan                  35
Pennsylvania                  29
Wisconsin                     26
Manitoba                      26
Connecticut                   24
New Hampshire                 14
Colorado                      14
Missouri                      13
North Dakota                  13
Ohio                          13
Maryland                      12
Alaska                        12
Nova Scotia                   11
Indiana                       11
Texas                         10
Florida                       10
Arizona                        9
Vermont                        8
Georgia                        7
Washington                     5
Virginia                       5
Newfoundland and Labrador      5
New Brunswick                  5
Iowa                           4
Maine                          4
Tennessee                      4
Yukon                          3
North Carolina                 3
South Dakota                   3
Rhode Island                   3
Prince Edward Island           2
Montana                        2
Oklahoma                       1
Delaware                       1
South Carolina                 1
Idaho                          1
Name: count, dtype: int64

In [63]:
### Group and aggregate stats by State_Province for USA and CAN players
state_prov_agg_stats = {
    "Games_Played": "sum",
    "G": "sum",
    "A": "sum",
    "Pts": "sum",
    "PlusMinus": "sum",
    "Shots": "sum",
    "TOI_sec": "sum",
    "PIM": "sum",
}

state_prov_agg_df = us_can_df.groupby("State_Province").agg(state_prov_agg_stats).reset_index()
print(state_prov_agg_df.head(20))

## Get count of players in each State_Province and calculate per player averages
state_prov_player_counts = (us_can_df["State_Province"]
                    .value_counts(dropna=False)
                    .fillna(0).astype(int))
print("Player Counts by State/Province")
print(state_prov_player_counts.reset_index().rename(columns={"index":"State/Province","State_Province":" Count"}))

### Divide aggregated stats by player counts to get per player averages by State_Province
state_prov_player_counts = state_prov_player_counts.reindex(state_prov_agg_df["State_Province"])
for stat in state_prov_agg_stats.keys():
    state_prov_agg_df[stat + "_per_player"] = state_prov_agg_df[stat] / state_prov_player_counts.values

## Calculate rate stats per 60 minutes for each aggregated stat by State_Province
for stat in state_prov_agg_stats.keys():
    state_prov_agg_df[stat + "_per_60min"] = (state_prov_agg_df[stat] / state_prov_agg_df["TOI_sec"]) * 3600

# Calculate per game averages for each aggregated stat by State_Province
for stat in state_prov_agg_stats.keys():
    state_prov_agg_df[stat + "_per_player_per_game_played"] = state_prov_agg_df[stat] / state_prov_agg_df["Games_Played"]
# state_prov_agg_df.info()
# state_prov_agg_df.head(20)

      State_Province  Games_Played    G    A  Pts  PlusMinus  Shots  \
0             Alaska            84   19   28   47          0    160
1            Alberta           770  121  190  311        -51   1134
2            Arizona            86    8   31   39          3     94
3   British Columbia           796  113  206  319        -21   1237
4         California           293   42   73  115         -2    424
5           Colorado            88    6   14   20          7     94
6        Connecticut           166   16   42   58          5    264
7           Delaware             8    1    2    3          2      4
8            Florida            88   19   37   56          8    152
9            Georgia            47    5   12   17          1     65
10             Idaho             9    1    2    3         -1      7
11          Illinois           457   60  122  182         28    697
12           Indiana            90   10   14   24        -16    106
13              Iowa            38    4    7   11         -4     52
14             Maine            28    0    2    2         -8      8
15          Manitoba           225   36   62   98         -7    380
16          Maryland            89   18   31   49         10    140
17     Massachusetts           447   61  107  168          1    669
18          Michigan           515   71  128  199        -44    838
19         Minnesota          1552  287  419  706         43   2527

      TOI_sec  PIM
0     86195.0   28
1    686523.0  424
2     75748.0   65
3    716463.0  439
4    246659.0  174
5     73582.0   56
6    148675.0   58
7      6183.0    2
8     84875.0   72
9     34533.0   55
10    12901.0    4
11   432840.0  266
12    70414.0   34
13    31716.0   51
14    16825.0    8
15   214278.0   94
16    74121.0   34
17   410267.0  219
18   477942.0  336
19  1469516.0  707
Player Counts by State/Province
                        Count  count
0                   Minnesota    181
1                     Ontario    174
2            British Columbia    106
3                     Alberta     98
4                    New York     84
5               Massachusetts     69
6                    Michigan     68
7                      Quebec     66
8                    Illinois     53
9                  California     45
10                 New Jersey     37
11               Saskatchewan     35
12               Pennsylvania     29
13                  Wisconsin     26
14                   Manitoba     26
15                Connecticut     24
16              New Hampshire     14
17                   Colorado     14
18                   Missouri     13
19               North Dakota     13
20                       Ohio     13
21                   Maryland     12
22                     Alaska     12
23                Nova Scotia     11
24                    Indiana     11
25                      Texas     10
26                    Florida     10
27                    Arizona      9
28                    Vermont      8
29                    Georgia      7
30                 Washington      5
31                   Virginia      5
32  Newfoundland and Labrador      5
33              New Brunswick      5
34                       Iowa      4
35                      Maine      4
36                  Tennessee      4
37                      Yukon      3
38             North Carolina      3
39               South Dakota      3
40               Rhode Island      3
41       Prince Edward Island      2
42                    Montana      2
43                   Oklahoma      1
44                   Delaware      1
45             South Carolina      1
46                      Idaho      1

## MAKE A MAP/S FOR REDACTED CHARTS ON REDDIT

In [64]:
# # Check path of shapefile

# shapefile_path = "../../data/vault/10m_state_province_file.shp"

# # try to load file
# with

In [65]:
break

SyntaxError: 'break' outside loop (668683560.py, line 1)

In [ ]:
import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path



def plot_state_prov_choropleth(
    state_prov_agg_df: pd.DataFrame,
    metric: str = "G",                     # or "Pts"
    shapefile_path: str = "..\\..\\data\\vault\\state_province_geo\\ne_110m_admin_1_states_provinces.shp",
    output_path: str | Path = "state_prov_map_G.png",
    title: str | None = None,
    cmap: str = "YlGnBu",                  # nice smooth gradient
    dpi: int = 300
):
    """
    Plot a static choropleth map of US states + Canadian provinces using
    state_prov_agg_df, which must have columns:
        - 'State_Province'
        - the chosen metric (e.g. 'G' or 'Pts')
    """

    # --- load the shapefile ---
    admin1 = gpd.read_file(shapefile_path)

    # Natural Earth usually has both 'name' and 'name_en'
    # After admin1 = gpd.read_file(shapefile_path)

    # See what columns you have (optional, but handy):
    print("Shapefile columns:", admin1.columns.tolist())

    # Try a few common field names
    candidate_cols = ["name_en", "name", "name_1", "NAME_1", "state_name", "STATE_NAME"]
    name_col = None
    for col in candidate_cols:
        if col in admin1.columns:
            name_col = col
            break

    if name_col is None:
        raise ValueError(
            "Could not find a suitable name column in shapefile. "
            "Available columns are: "
            + ", ".join(admin1.columns.astype(str))
        )

    admin1["region_name"] = admin1[name_col]

    

    # Keep only USA + Canada to match your table
    mask = admin1["admin"].isin(["United States of America", "Canada"])
    regions = admin1.loc[mask].copy()

    # --- join your data onto the geometry ---
    # Make sure the key column is string
    state_prov_agg_df = state_prov_agg_df.copy()
    state_prov_agg_df["State_Province"] = state_prov_agg_df["State_Province"].astype(str)

    merged = regions.merge(
        state_prov_agg_df,
        left_on="region_name",
        right_on="State_Province",
        how="left",
        validate="1:1"
    )

    if metric not in merged.columns:
        raise ValueError(f"Metric '{metric}' is not a column in the dataframe.")

    # --- plotting ---
    fig, ax = plt.subplots(figsize=(8, 10))  # tweak for aspect/Reddit

    # Blank-ish style: no axes, white background
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    # Draw boundaries lightly so it's minimalist
    merged.boundary.plot(ax=ax, linewidth=0.3, color="lightgrey")

    # Choropleth fill
    merged.plot(
        column=metric,
        ax=ax,
        cmap=cmap,
        linewidth=0.4,
        edgecolor="black",
        legend=True,
        legend_kwds={
            "label": metric,
            "shrink": 0.5,
            "orientation": "vertical"
        },
        missing_kwds={
            "color": "white",
            "edgecolor": "lightgrey",
            "hatch": "///",
            "label": "No data"
        }
    )

    # Nicely centered, mostly-blank map
    ax.set_axis_off()
    ax.set_aspect("equal")

    if title is None:
        title = f"{metric} by State / Province (College Hockey)"
    ax.set_title(title, fontsize=14, fontweight="bold", pad=12)

    # Optional subtitle / data source
    # ax.text(0.5, 0.03, "Data: Your College Hockey DB",
    #         transform=fig.transFigure, ha="center", va="bottom", fontsize=9)

    plt.tight_layout()
    output_path = Path(output_path)
    fig.savefig(output_path, dpi=dpi, bbox_inches="tight", facecolor="white")
    # plt.close(fig)
    # Show the plot
    plt.show()

    print(f"Map saved to: {output_path}")



## Call the function to plot goals by state/province
plot_state_prov_choropleth(
    state_prov_agg_df=state_prov_agg_df,
    metric="G",
    shapefile_path="../../data/vault/10m_state_province_file.shp",
    output_path=plot_folder / "state_prov_map_G.png",
    title="Goals by State / Province (College Hockey)",
    cmap="YlGnBu",
    dpi=300
)